# Generated by Django 6.0 on 2026-01-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(default=None, upload_to='image/'),
            preserve_default=False,
        ),
    ]
