# Generated by Django 6.0 on 2026-01-20 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_fooditem_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fooditem',
        ),
    ]
